name: Every 5 Minutes Workflow Test

on:
  schedule:
    - cron: '*/5 * * * *'    # Runs every 5 minutes
  workflow_dispatch:           # Enables manual run

jobs:
  test-run:
    runs-on: ubuntu-latest

    steps:
      - name: Echo my email 24f2008070@ds.study.iitm.ac.in
        run: echo "This is a test run every 5 minutes for 24f2008070@ds.study.iitm.ac.in"
